"use client";

import { Suspense, useEffect, useState, useMemo } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import {
  Shield,
  FileText,
  Phone,
  Building2,
  Lock,
  Send,
  CheckCircle2,
  Loader2,
  ArrowLeft,
  Radio,
  RefreshCw,
} from "lucide-react";
import Link from "next/link";

type StepStatus = "pending" | "active" | "done";

interface AgentStep {
  id: string;
  label: string;
  sublabel: string;
  icon: typeof Shield;
  durationMs: number;
}

const AGENT_STEPS: AgentStep[] = [
  { id: "confirm", label: "Threat confirmed", sublabel: "HIGH_RISK verdict locked — autonomous mode engaged", icon: Shield, durationMs: 700 },
  { id: "draft", label: "Drafting PDRM / NSRC report", sublabel: "Populating NSRC template with incident metadata", icon: FileText, durationMs: 900 },
  { id: "submit", label: "Submitting to National Scam Response Centre", sublabel: "Routing via NSRC channel · Ref queued", icon: Send, durationMs: 750 },
  { id: "bank", label: "Contacting partner bank", sublabel: "Freeze & reversal API — CIMB / Maybank gateway", icon: Building2, durationMs: 850 },
  { id: "freeze", label: "Account freeze initiated", sublabel: "Outbound transfers blocked · reversal window open", icon: Lock, durationMs: 700 },
  { id: "call", label: "Voice agent on standby", sublabel: "PDRM hotline script prepared (demo)", icon: Phone, durationMs: 650 },
  { id: "sync", label: "Syncing threat intelligence", sublabel: "Firebase national database updated", icon: Radio, durationMs: 600 },
];

function buildDemoDraft(message: string, scamType: string, refId: string) {
  const date = new Date().toLocaleDateString("en-MY", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  return `[OFFICIAL INITIAL REPORT DRAFT — NSRC]
Reference: ${refId}
Date: ${date}
Channel: SoloFraud Autonomous Agent

1. INCIDENT SUMMARY
${scamType} detected via autonomous analyzer (${(message.slice(0, 120) + (message.length > 120 ? "…" : "")).trim()})

2. SCAMMER INDICATORS
Extracted from message metadata — links, urgency language, impersonation cues.

3. FINANCIAL IMPACT
Potential unauthorized transfer — freeze requested pending victim confirmation.

4. ACTIONS TAKEN (AUTONOMOUS)
• PDRM e-report draft generated
• NSRC routing prepared (997)
• Partner bank freeze API invoked (demo)
• Account reversal window flagged

5. COMPLAINANT STATEMENT
I wish to lodge this report and request immediate account protection.

— Generated by SoloFraud Autonomous Rescue Agent`;
}

function RescuePageContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [activeIndex, setActiveIndex] = useState(-1);
  const [complete, setComplete] = useState(false);
  const [typedChars, setTypedChars] = useState(0);

  const message = searchParams.get("msg") ?? "";
  const scamType = searchParams.get("type") ?? "Scam attempt";
  const refId =
    searchParams.get("ref") ??
    `NSRC-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 90000) + 10000).padStart(5, "0")}`;

  const fullDraft = useMemo(
    () => buildDemoDraft(message, scamType, refId),
    [message, scamType, refId]
  );

  useEffect(() => {
    if (!message) {
      router.replace("/");
      return;
    }

    let cancelled = false;
    let stepIdx = 0;
    let timeout: ReturnType<typeof setTimeout>;

    const runStep = () => {
      if (cancelled) return;
      setActiveIndex(stepIdx);

      timeout = setTimeout(() => {
        if (cancelled) return;
        stepIdx += 1;
        if (stepIdx < AGENT_STEPS.length) {
          runStep();
        } else {
          setComplete(true);
        }
      }, AGENT_STEPS[stepIdx].durationMs);
    };

    const startDelay = setTimeout(runStep, 400);
    return () => {
      cancelled = true;
      clearTimeout(startDelay);
      clearTimeout(timeout);
    };
  }, [message, router]);

  useEffect(() => {
    if (!complete) return;
    const interval = setInterval(() => {
      setTypedChars((c) => {
        if (c >= fullDraft.length) {
          clearInterval(interval);
          return c;
        }
        return c + Math.min(12, fullDraft.length - c);
      });
    }, 28);
    return () => clearInterval(interval);
  }, [complete, fullDraft]);

  const getStepStatus = (i: number): StepStatus => {
    if (complete || i < activeIndex) return "done";
    if (i === activeIndex) return "active";
    return "pending";
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      style={{ maxWidth: 900, margin: "0 auto", padding: "32px 24px 64px" }}
    >
      <Link
        href="/"
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: 8,
          fontSize: 13,
          fontWeight: 600,
          color: "#6B7E8C",
          marginBottom: 24,
          textDecoration: "none",
        }}
      >
        <ArrowLeft size={16} />
        Back to Analyzer
      </Link>

      <div style={{ textAlign: "center", marginBottom: 32 }}>
        <motion.div
          animate={complete ? { scale: [1, 1.05, 1] } : {}}
          transition={{ duration: 0.5 }}
          style={{
            display: "inline-flex",
            padding: 14,
            borderRadius: 20,
            background: complete ? "rgba(90,155,181,0.12)" : "rgba(213,55,70,0.08)",
            marginBottom: 16,
          }}
        >
          {complete ? (
            <CheckCircle2 size={40} style={{ color: "#5a9bb5" }} />
          ) : (
            <motion.div animate={{ rotate: 360 }} transition={{ duration: 2, repeat: Infinity, ease: "linear" }}>
              <RefreshCw size={40} style={{ color: "#D53746" }} />
            </motion.div>
          )}
        </motion.div>
        <h1 style={{ fontSize: "clamp(24px, 4vw, 36px)", fontWeight: 800, color: "#2c3e50", marginBottom: 8 }}>
          {complete ? "Autonomous Rescue Complete" : "Autonomous Agent Executing"}
        </h1>
        <p style={{ fontSize: 14, color: "#9aabb8", maxWidth: 480, margin: "0 auto" }}>
          {complete
            ? "Police report drafted · bank freeze signalled · reversal window flagged (demo visualization)"
            : "No user action required — agent is drafting reports and contacting institutions"}
        </p>
        <span
          className="badge"
          style={{
            display: "inline-block",
            marginTop: 12,
            background: "rgba(213,55,70,0.08)",
            color: "#D53746",
            border: "1px solid rgba(213,55,70,0.2)",
            fontSize: 11,
            fontWeight: 700,
          }}
        >
          REF {refId}
        </span>
      </div>

      <motion.div className="glass-card-static" style={{ padding: 24, marginBottom: 24 }}>
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {AGENT_STEPS.map((step, i) => {
            const status = getStepStatus(i);
            const Icon = step.icon;
            return (
              <motion.div
                key={step.id}
                initial={{ opacity: 0, x: -12 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.05 }}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 16,
                  padding: "14px 16px",
                  borderRadius: 14,
                  background:
                    status === "active"
                      ? "rgba(213,55,70,0.06)"
                      : status === "done"
                        ? "rgba(90,155,181,0.05)"
                        : "rgba(53,71,97,0.02)",
                  border: `1px solid ${
                    status === "active"
                      ? "rgba(213,55,70,0.15)"
                      : status === "done"
                        ? "rgba(90,155,181,0.12)"
                        : "rgba(53,71,97,0.06)"
                  }`,
                }}
              >
                <motion.div
                  animate={status === "active" ? { scale: [1, 1.08, 1] } : {}}
                  transition={{ duration: 0.8, repeat: status === "active" ? Infinity : 0 }}
                  style={{
                    width: 44,
                    height: 44,
                    borderRadius: 12,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    background:
                      status === "done"
                        ? "rgba(90,155,181,0.15)"
                        : status === "active"
                          ? "rgba(213,55,70,0.12)"
                          : "rgba(53,71,97,0.06)",
                  }}
                >
                  {status === "active" ? (
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                    >
                      <Loader2 size={20} style={{ color: "#D53746" }} />
                    </motion.div>
                  ) : status === "done" ? (
                    <CheckCircle2 size={20} style={{ color: "#5a9bb5" }} />
                  ) : (
                    <Icon size={20} style={{ color: "#9aabb8" }} />
                  )}
                </motion.div>
                <motion.div style={{ flex: 1, minWidth: 0 }}>
                  <motion.div
                    style={{
                      fontSize: 14,
                      fontWeight: 700,
                      color: status === "pending" ? "#9aabb8" : "#354761",
                    }}
                  >
                    {step.label}
                  </motion.div>
                  <motion.p style={{ fontSize: 12, color: "#9aabb8", marginTop: 2 }}>{step.sublabel}</motion.p>
                </motion.div>
                <AnimatePresence>
                  {status === "active" && (
                    <motion.div
                      initial={{ opacity: 0, width: 0 }}
                      animate={{ opacity: 1, width: 80 }}
                      exit={{ opacity: 0 }}
                      className="risk-meter"
                      style={{ height: 4, background: "rgba(53,71,97,0.08)", overflow: "hidden", borderRadius: 2 }}
                    >
                      <motion.div
                        style={{
                          height: "100%",
                          background: "linear-gradient(90deg, #D53746, #F4A4B4)",
                          borderRadius: 2,
                        }}
                        animate={{ width: ["0%", "100%"] }}
                        transition={{ duration: AGENT_STEPS[i].durationMs / 1000, ease: "easeInOut" }}
                      />
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>
      </motion.div>

      <AnimatePresence>
        {complete && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass-card-static"
            style={{
              padding: 24,
              border: "1px solid rgba(90,155,181,0.2)",
              background: "linear-gradient(180deg, rgba(90,155,181,0.06) 0%, rgba(255,255,255,0.85) 100%)",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
              <FileText size={20} style={{ color: "#354761" }} />
              <h2 style={{ fontSize: 16, fontWeight: 700, color: "#354761" }}>
                Police & Bank Report Draft
              </h2>
            </div>
            <pre
              style={{
                fontFamily: "JetBrains Mono, ui-monospace, monospace",
                fontSize: 11,
                lineHeight: 1.6,
                color: "#6B7E8C",
                whiteSpace: "pre-wrap",
                margin: 0,
                maxHeight: 320,
                overflowY: "auto",
                padding: 16,
                borderRadius: 12,
                background: "rgba(53,71,97,0.04)",
                border: "1px solid rgba(53,71,97,0.08)",
              }}
            >
              {fullDraft.slice(0, typedChars)}
              {typedChars < fullDraft.length && (
                <motion.span
                  animate={{ opacity: [1, 0] }}
                  transition={{ duration: 0.5, repeat: Infinity }}
                  style={{ color: "#82BCD5" }}
                >
                  ▌
                </motion.span>
              )}
            </pre>
            <p style={{ fontSize: 11, color: "#9aabb8", marginTop: 14, textAlign: "center" }}>
              Demo visualization only — no real calls or bank APIs are invoked.
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function RescuePage() {
  return (
    <Suspense
      fallback={
        <div
          style={{
            minHeight: "60vh",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            gap: 8,
          }}
        >
          <div style={{ display: "flex", gap: 6 }}>
            <div className="typing-dot" />
            <div className="typing-dot" />
            <div className="typing-dot" />
          </div>
          <p style={{ fontSize: 14, color: "#9aabb8", marginTop: 8 }}>Loading autonomous rescue…</p>
        </div>
      }
    >
      <RescuePageContent />
    </Suspense>
  );
}
